.sym <- list(
  EOF = 'EOF',
  EOL = '\n',
  EQUALS = '=',
  COMMENT = '#',
  LPAREN = '(',
  RPAREN = ')',
  LBRACKET = '[',
  RBRACKET = ']',
  LBRACE = '}',
  RBRACE = '{',
  LESSTHAN = '<',
  MINUS = '-',
  COLON = ':',
  PERIOD = '.',
  BACKTICK = '`',
  SINGLEQUOTE = "'",
  DOUBLEQUOTE = '"',
  DOLLARSIGN = '$',
  BACKSLASH = '\\',
  EXPNOTATION = 'e',
  NUMBER = '[0-9.e]',
  LETTER = '[a-zA-Z]',
  ASSIGNOP = '(=|<-)',
  FILENAME_CHAR = '[^$]',
  # syntactic variable names, see ?Quotes
  SYNTACTIC_CHAR = '[\\w.]',
  # quoted characters are anything except a backtick
  QUOTED_CHAR = '[^`]',
  IDENTIFIER_CHAR = '[`a-zA-Z.]',
  TINSEL_COMMENT = '#.',
  PACKAGE_ACCESSOR = '::'
)

.type <- list(
  PROGRAM = 1,
  STATEMENT_LIST = 2,
  STATEMENT = 3,
  TINSEL_STATEMENT = 4,
  REXPRESSION = 5,
  DECORATORS = 6,
  DECORATOR = 7,
  TINSEL_COMMENT = 8,
  FILE_REFERENCE = 9,
  FUNCTION_REFERENCE = 10,
  FILE_NAME = 11,
  EXTRACT_OPERATOR = 12,
  IDENTIFIER = 13,
  ARGUMENT_LIST = 14,
  ARGUMENT = 15,
  PARAMETER_NAME = 16,
  ARGUMENT_VALUE = 17,
  DECORATEE = 18,
  ASSIGN_OPERATOR = 19,
  FUNCTION_NAME = 20,
  FUNCTION_DEFINITION = 21,
  FUNCTION_OPERATOR = 22,
  PARAMETER_LIST = 23,
  PARAMETER = 24,
  LPAREN = 25,
  RPAREN = 26,
  SHIFT = 93,
  REDUCE = 94,
  EMPTY = 95,
  EOL = 96,
  EOF = 97,
  UNKNOWN = 98,
  LOOKAHEAD = 99
)

.reserved <- c(
  'if', 'else', 'repeat', 'while', 'function', 'for', 'in',
  'next', 'break', 'TRUE', 'FALSE', 'NULL', 'Inf', 'NaN', 'NA',
  'NA_integer_', 'NA_real_', 'NA_complex_', 'NA_character_', '...'
)
