.sym <- list(
  EOF = 'EOF',
  EOL = '\n',
  EQUALS = '=',
  COMMENT = '#',
  LPAREN = '(',
  RPAREN = ')',
  LBRACKET = '[',
  RBRACKET = ']',
  LBRACE = '}',
  RBRACE = '{',
  LESSTHAN = '<',
  MINUS = '-',
  COLON = ':',
  PERIOD = '.',
  BACKTICK = '`',
  SINGLEQUOTE = "'",
  DOUBLEQUOTE = '"',
  DOLLARSIGN = '$',
  BACKSLASH = '\\',
  EXPNOTATION = 'e',
  NUMBER = '[0-9.e]',
  LETTER = '[a-zA-Z]',
  ASSIGNOP = '(=|<-)',
  FILENAME_CHAR = '[^$]',
  # syntactic variable names, see ?Quotes
  SYNTACTIC_CHAR = '[\\w.]',
  # quoted characters are anything except a backtick
  QUOTED_CHAR = '[^`]',
  IDENTIFIER_CHAR = '[`a-zA-Z.]',
  TINSEL_COMMENT = '#.',
  PACKAGE_ACCESSOR = '::'
)

.type <- list(
  FILE_REFERENCE = 1,
  ASSIGNMENT = 2,
  DECORATOR = 3,
  IDENTIFIER = 4,
  PACKAGE_ACCESSOR = 5,
  TINSEL_COMMENT = 6,
  RESERVED = 7,
  STRING = 8,
  NUMBER = 9,
  PACKAGE_NAME = 10,
  DECORATEE = 11,
  CALL = 12,
  DECORATORS = 13,
  TINSEL_EXPR = 14,
  FILE_NAME = 15,
  FILE_ACCESSOR = 16,
  FUNCTION_NAME = 17,
  EQUALS = 18,
  EXPRESSION = 19,
  FUNCTION_REFERENCE = 20,
  LPAREN = 22,
  ARGUMENTS = 23,
  RPAREN = 24,
  ASSIGNOP = 25,
  FUNCTION_DEC = 26,
  FUNCTION_STMT = 27,
  RELATIONALOP = 28,
  EXTRACTOP = 29,
  SOF = 95,
  EOL = 96,
  EOF = 97,
  UNKNOWN = 98,
  LOOKAHEAD = 99
)

.reserved <- c(
  'if', 'else', 'repeat', 'while', 'function', 'for', 'in',
  'next', 'break', 'TRUE', 'FALSE', 'NULL', 'Inf', 'NaN', 'NA',
  'NA_integer_', 'NA_real_', 'NA_complex_', 'NA_character_', '...'
)
